### ISSUE TITLE
Version 3.6 breaks NVDA+B

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/WorldVoice#10]
I'm using WorldVoice-version 3.6 and I get the following error when I press NVDA+B.
```log
IO - speech.speech.speak (17:56:53.603) - MainThread (3144):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - inputCore.InputManager.executeGesture (17:56:55.483) - winInputHook (13176):
Input: kb(laptop):NVDA+b
ERROR - scriptHandler.executeScript (17:56:55.483) - MainThread (3144):
error executing script: <bound method GlobalCommands.script_speakForeground of <globalCommands.GlobalCommands object at 0x04DDF6F0>> with gesture 'NVDA+b'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 2698, in script_speakForeground
  File "C:\Users\cary-rowen\AppData\Roaming\nvda\addons\WorldVoice\synthDrivers\WorldVoice\sayAll.py", line 53, in readObjects
    reader = _ObjectsReader(self, obj)
NameError: name '_ObjectsReader' is not defined
IO - inputCore.InputManager.executeGesture (17:56:56.694) - winInputHook (13176):
Input: kb(laptop):shift+control+NVDA+f1
```

**Comment by lbk2907** [comment]
I’m facing the same issue here.

**Comment by tsengwoody** [comment]
version 3.7 fixed this issue
